config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'
  get '/menu', to: 'welcomes#menu'
  #get '/offer', to: 'welcomes#offer'
  #get '/offers/:offer_id', to: 'offers#details', as: 'details'
  get '/about_us', to: 'welcomes#about_us'
  get '/contact_us', to: 'welcomes#contact_us'
  post '/send_message', to: 'welcomes#send_message'
  post '/add_to_cart', to: 'carts#add_to_cart'
  get '/subscription', to: 'charges#subscription'
  post '/create_subscription', to: 'charges#create_subscription'

  get '/invoice_email', to: 'users#invoice_email' 
  get '/order_history/', to: 'charges#order_history'
  #delete '/order_destroy/:id', to: 'charges#order_destroy'
  #get '/order_show/:id', to: 'charges#order_show'
  #get '/carts/:id', to: 'carts#pdf_invoice
  resources :carts, only: [:show]
  resources :charges
  resources :offers, only: [:index, :show]
  resources :cart_items, only: [:edit, :update, :destroy] do
    collection do
      delete :delete_all
    end
  end
  resources :invoices, only: [:show] 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  enum status: [:paid, :unpaid]
  validates :status, presence: true
  belongs_to :cart
  belongs_to :food_item
  belongs_to :order, required: false
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name,:price, presence: true
  belongs_to :category
  has_one :cart_item
  has_and_belongs_to_many :offers, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  
  belongs_to :user
  belongs_to :order
  
  after_create :send_mail_to_user

  def send_mail_to_user
    UserMailer.with(user: self.user,order: self.order).invoice_email.deliver_now
  end 
end

app/models/offer.rb
class Offer < ApplicationRecord
  attr_accessor :food_items_ids
  enum status: [:active, :inactive]
  has_and_belongs_to_many :food_items, dependent: :destroy
  validates :start_time, :end_time, :title, :status, presence: true
  after_save :add_food_items

  def add_food_items
    self.food_items_ids.each do |id|
      unless self.food_items.pluck(:id).include?(id.to_i) 
        self.food_items << FoodItem.find(id)
      end
    end   
  end  
end

app/models/order.rb
require "pdfkit"
require "render_anywhere"
class Order < ApplicationRecord
  include RenderAnywhere
  validates :ammount, :status,presence: true
  belongs_to :user
  has_one :invoice
  has_many :cart_items
  has_one :subscription
  #after_create :generate_pdf_of_invoice 
  def create_invoice
    Invoice.create(user_id: user.id, order_id: id)
  end

  def generate_pdf_of_invoice
    kit = PDFKit.new(as_htmls, page_size: 'A4')
    kit.to_file("invoice.pdf")
  end
  def as_htmls
    render template: "carts/pdf_invoice",layout: "invoice_pdf", locals: { order: self}
  end

  def generate_pdf_of_subscription
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("subscription.pdf")
  end

  def as_html
    render template: "carts/subscription_pdf",layout: "invoice_pdf", locals: { subscription: self.subscription}
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
	validates :plan_name, :price, :no_of_days, presence: true
	has_many :subscriptions
end

app/models/send_message.rb
class SendMessage < ApplicationRecord
	validates :name, :message, :email, :subject, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	validates :expiry_date, presence: true
	belongs_to :plan
	belongs_to :user
	belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable     
  validates :first_name, :last_name, :address, :contact_no, presence: true
  has_one :cart
  has_many :orders
  has_many :invoices
  has_many :subscriptions
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:add_to_cart, :show]
  def add_to_cart
    cart = current_user.cart.present? ? current_user.cart : Cart.create(user_id: current_user.id)
    @cart_item = cart.cart_items.find_or_create_by(food_item_id: params[:cart_item][:food_item_id], status:"unpaid")
    @cart_item.update(quantity: params[:cart_item][:quantity])
    @offer = Offer.find_by(id: params[:cart_item][:offer_id])
    if @offer.present?
      redirect_to offer_path(@offer)
    else
      redirect_to menu_path
    end
  end
  
  def show
    @cart = Cart.find(params[:id])
    @unpaid_cart_items = @cart.cart_items.unpaid
    @offer = Offer.find_by(id: params[:offer_id])
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :authenticate_user!, :except => [:index,:about_us,:contact_us]
  def index

  end

  def about_us
  end

  def contact_us

  end

  def send_message
    message = SendMessage.new(contact_params)
    if message.save
      flash[:success] = 'Message has sent successfully.'
      redirect_to contact_us_path
    else
      flash[:error] = 'Somthing went wrong try again..'
    end 
  end

  def menu
    @categories = Category.includes(:food_items)
  end

  private

  def contact_params
    params.require(:contact).permit(:message, :name, :email, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_flash_message
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

  def food_item_quantity(food_item_id)
    cart_item = current_user.cart.cart_items.where(food_item_id: food_item_id).first
    if cart_item
      cart_item.quantity
    else
      0
    end
  end
  def calculate_amount
    @amount = 0
    current_user.cart.cart_items.unpaid.each do |cartitem|
      @amount = @amount + cartitem.food_item.price*cartitem.quantity
    end
    @amount
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcomes/about_us.html.erb
  <!-- breadcrumb start -->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>About Us</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <!-- breadcrumb end -->

  <!-- about part start -->
<section class="about_part about_bg">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-sm-4 col-lg-5 offset-lg-1">
          <%= image_tag("about.png", :alt => "about feed") %>
      </div>
      <div class="col-sm-8 col-lg-4">
        <div class="about_text">
          <h5>Our History</h5>
          <h2>Where The Food’s As Good
              As The Root Beer.</h2>
          <h4>Satisfying people hunger for simple pleasures</h4>
          <p>May over was. Be signs two. Spirit. Brought said dry own firmament lesser best sixth deep
              abundantly bearing, him, gathering you
              blessed bearing he our position best ticket in month hole deep </p>
          <a href="#" class="btn_3">Read More <%= image_tag("icon/left_2.svg", :alt => "left_2 feed") %></a>
        </div>
      </div>
    </div>
  </div>
</section>
  <!-- about part end -->

app/views/welcomes/contact_us.html.erb
<!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg">
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="breadcrumb_iner text-center">
        <div class="breadcrumb_iner_item">
          <h2>Contact Us</h2>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
  <!-- breadcrumb start-->

  <!-- ================ contact section start ================= -->
<section class="contact-section section_padding">
  <div class="container">
    <div class="d-none d-sm-block mb-5 pb-4">
      <div id="map" style="height: 480px;"></div>
      <!-- <script>
        function initMap() {
          var uluru = {
            lat: -25.363,
            lng: 131.044
          };
          var grayStyles = [{
              featureType: "all",
              stylers: [{
                  saturation: -90
                },
                {
                  lightness: 50
                }
              ]
            },
            {
              elementType: 'labels.text.fill',
              stylers: [{
                color: '#ccdee9'
              }]
            }
          ];
          var map = new google.maps.Map(document.getElementById('map'), {
            center: {
              lat: -31.197,
              lng: 150.744
            },
            zoom: 9,
            styles: grayStyles,
            scrollwheel: false
          });
        }
      </script>
      
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_f85uAsatgGMN5xDY1yVmXEWEdJ2IVYU&callback=initMap">
      </script> -->
      <div class="col-md-6">
        <input id="pac-input" class="controls" type="text" placeholder="Search Box">
        <div id="map"></div>
      </div>
      <script type="text/javascript" >
        var lat = 0.0;
        var long = 0.0;
        function initMap() {
          var uluru = {lat: parseFloat(lat), lng: parseFloat(long)};
          var map = new google.maps.Map(
            document.getElementById('map'), {zoom: 10, center: uluru});
          var marker = new google.maps.Marker({position: uluru, map: map});
          var input = document.getElementById('pac-input');
          var searchBox = new google.maps.places.SearchBox(input);
          map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

              // Bias the SearchBox results towards current map's viewport.
          map.addListener('bounds_changed', function() {
            searchBox.setBounds(map.getBounds());
          });
          var markers = [];
              // Listen for the event fired when the user selects a prediction and retrieve
              // more details for that place.
          searchBox.addListener('places_changed', function() {
            var places = searchBox.getPlaces();

            if (places.length == 0) {
              return;
            }

            // Clear out the old markers.
            markers.forEach(function(marker) {
              marker.setMap(null);
            });
            markers = [];

            // For each place, get the icon, name and location.
            var bounds = new google.maps.LatLngBounds();
            places.forEach(function(place) {
              if (!place.geometry) {
                console.log("Returned place contains no geometry");
                return;
              }
              var icon = {
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(25, 25)
              };

              // Create a marker for each place.
              markers.push(new google.maps.Marker({
                map: map,
                icon: icon,
                title: place.name,
                position: place.geometry.location
              }));

              if (place.geometry.viewport) {
                // Only geocodes have viewport.
                bounds.union(place.geometry.viewport);
              } else {
                bounds.extend(place.geometry.location);
              }
            });
            map.fitBounds(bounds);
          });
        }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHuv_3XrQ2H0V5apY0QAPDs8IBtoUNaCo&libraries=places&callback=initMap">
      </script>
    </div>
    <div class="row">
      <div class="col-12">
        <h2 class="contact-title">Get in Touch</h2>
      </div>
      <div class="col-lg-8">
      <%= form_for :contact, url: send_message_path, html: {class: 'contact_form', id: 'contact_form'} do |f| %>
      <div class="row">
        <div class="col-12">
          <div class="form-group">
            <%= f.text_area :message, :size => "30x9", autofocus: true, autocomplete: "message",placeholder: " Enter Message", class: 'form-control messageField' %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.text_field :name, autofocus: true, autocomplete: "name",placeholder: "Name", class: 'form-control nameField' %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder: "Email", class: 'form-control emailField' %>
          </div>
        </div>
        <div class="col-12">
          <div class="form-group">
            <%= f.text_field :subject, autofocus: true, autocomplete: "subject",placeholder: "Subject", class: 'form-control subjectField' %>
          </div>
        </div>
      </div>
        <div class="form-group mt-3">
          <div class="actions">
            <button type="submit" class="button button-contactForm btn_4">Send Message</button>
          </div>
        </div>
      <%end%>
    </div>
      <div class="col-lg-4">
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-home"></i></span>
          <div class="media-body">
            <h3>Buttonwood, California.</h3>
            <p>Rosemead, CA 91770</p>
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-tablet"></i></span>
          <div class="media-body">
            <h3>00 (440) 9865 562</h3>
            <p>Mon to Fri 9am to 6pm</p>
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-email"></i></span>
          <div class="media-body">
            <h3>support@colorlib.com</h3>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================ contact section end ================= -->

app/views/welcomes/menu.html.erb
 <!-- breadcrumb start -->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Food Menu</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
 <!-- breadcrumb end -->

  <!-- modal part start -->
<%if current_user.cart.cart_items.unpaid.present?%>
  <div id="modal-window" class="modal hide fade" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">Your Cart Having items
          Do You Want To</h5>
        </div>
        <div class="modal-body">
          <p text-color="olive">
            <i>
              <%= link_to "Continue", cart_path(current_user.cart.id),:class => "btn_11" %>
              <%= link_to "Clear All", delete_all_cart_items_path, data: {:confirm => 'Are you sure?'}, :method => :delete,:class => "btn_11" %>
            </i>
          </p>
        </div> 
      </div>
    </div>
  </div> 
<%end%>
  <!-- modal part end -->

  <!--::menu_part start::-->
<section class="chefs_part blog_item_section section_padding">
  <div class="container">
    <div class="row">
      <div class="col-xl-5">
        <div class="section_tittle">
          <h2>Menu List Items</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <% @categories.where.not(name:'Monthly Thali').each do |category| %>
        <% if category.food_items.present? %>
          <%  category.food_items .each do |food_item| %>
            <div class="col-sm-6 col-lg-4">
              <div class="single_blog_item">
                <div class="single_blog_img">
                  <%= image_tag food_item.photo.url, :size => "350x200" %>
                </div>
                <div class="single_blog_text text-center">
                  <h3><%=food_item.name%></h3>
                  <p><%=food_item.price%></p>
                  <%if current_user.present? %> 
                    <%if current_user.cart.present? &&current_user.cart.cart_items.unpaid.map(&:food_item_id).include?(food_item.id)%>
                      Added
                    <%else%>
                      <%= form_for :cart_item,:url => add_to_cart_path  do |cart_item| %>
                        <button type="button" class="
                        add-quantity"><i class="fas fa-minus"></i></button>
                        <%= cart_item.text_field :quantity,class: 'qty', value: food_item_quantity(food_item.id) %>
                        <button type="button" class="add-quantity"><i class="fas fa-plus"></i></button>
                        <%= cart_item.hidden_field :food_item_id, :value => food_item.id %>
                        <button type="submit" class="add-button"><i class="fas fa-shopping-cart"></i></button>
                      <%end%>
                    <%end%> 
                  <%else%>
                    <%= form_for :cart_item,:url => add_to_cart_path  do |cart_item| %>
                      <button type="button" class="
                      add-quantity"><i class="fas fa-minus"></i></button>
                      <%= cart_item.text_field :quantity,class: 'qty', value: food_item_quantity(food_item.id) %>
                      <button type="button" class="add-quantity"><i class="fas fa-plus"></i></button>
                      <%= cart_item.hidden_field :food_item_id, :value => food_item.id %>
                      <button type="submit" class="add-button"><i class="fas fa-shopping-cart"></i></button>
                    <%end%>
                  <%end%>
                </div>
              </div>
            </div> 
          <%end%>
        <%end%>
      <%end%>
      <% @categories.where(name:'Monthly Thali').each do |category| %>
        <% if category.food_items.present? %>
          <%  category.food_items .each do |food_item| %>
            <div class="col-sm-6 col-lg-4">
              <div class="single_blog_item">
                <div class="single_blog_img">
                  <%= image_tag food_item.photo.url, :size => "350x200" %>
                </div>
                <div class="single_blog_text text-center">
                  <h3><%=food_item.name%></h3>
                  <p><%=food_item.price%></p>
                  <%if current_user.present? %> 
                    <%=link_to  subscription_path do %>
                      <i class="fas fa-shopping-cart" style="color:black"></i>
                    <%end%>
                  <%end%>
                </div>
              </div>
            </div> 
          <%end%>
        <%end%>
      <%end%>
    </div>
  </div> 
</section>
  <!--::menu_part end::-->
<%if session[:items] == "true"%>  
  <script>
    $(document).ready(function(){
      debugger
      $('#modal-window').modal('show');
      $('.btn_11').click(function(e){
        session[:items] = "false"
      });
      $(".qty").each(function(index, value) {
        value = parseInt(value["value"])
        if(value>0){
          $('.add-button').show();
        }else{
         $('.add-button').hide(); 
        }
      });
      $('.add-quantity').click(function(e){
        e.preventDefault();
        var element = $(this).siblings('.qty')
        if($(this).attr('class') == 'add-quantity'){
          $(element).val(parseInt(element.val()) + 1);  
        }else{
          if($(element).val() > 0){
           $(element).val(parseInt(element.val()) - 1);
         }
        }
        var button = $(this).siblings('.add-button')
        if(parseInt(element.val())>0){
          $(button).show();
        }else{
          $(button).hide();
        }
      });
    });
  </script>
<%else%>
  <script>
    $(document).ready(function(){
      $(".qty").each(function(index, value) {
        value = parseInt(value["value"])
        if(value>0){
          $('.add-button').show();
        }else{
         $('.add-button').hide(); 
        }
      });
      $('.add-quantity').click(function(e){
        e.preventDefault();
        var element = $(this).siblings('.qty')
        if($(this).attr('class') == 'add-quantity'){
          $(element).val(parseInt(element.val()) + 1);  
        }else{
          if($(element).val() > 0){
           $(element).val(parseInt(element.val()) - 1);
         }
        }
        var button = $(this).siblings('.add-button')
        if(parseInt(element.val())>0){
          $(button).show();
        }else{
          $(button).hide();
        }
      });
    });
  </script>
<%end%>