config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'
  get '/menu', to: 'welcomes#menu'
  #get '/offer', to: 'welcomes#offer'
  #get '/offers/:offer_id', to: 'offers#details', as: 'details'
  get '/about_us', to: 'welcomes#about_us'
  get '/contact_us', to: 'welcomes#contact_us'
  post '/send_message', to: 'welcomes#send_message'
  post '/add_to_cart', to: 'carts#add_to_cart'
  get '/subscription', to: 'charges#subscription'
  post '/create_subscription', to: 'charges#create_subscription'

  get '/invoice_email', to: 'users#invoice_email' 
  get '/order_history/', to: 'charges#order_history'
  #delete '/order_destroy/:id', to: 'charges#order_destroy'
  #get '/order_show/:id', to: 'charges#order_show'
  #get '/carts/:id', to: 'carts#pdf_invoice
  resources :carts, only: [:show]
  resources :charges
  resources :offers, only: [:index, :show]
  resources :cart_items, only: [:edit, :update, :destroy] do
    collection do
      delete :delete_all
    end
  end
  resources :invoices, only: [:show] 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  enum status: [:paid, :unpaid]
  validates :status, presence: true
  belongs_to :cart
  belongs_to :food_item
  belongs_to :order, required: false
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name,:price, presence: true
  belongs_to :category
  has_one :cart_item
  has_and_belongs_to_many :offers, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  
  belongs_to :user
  belongs_to :order
  
  after_create :send_mail_to_user

  def send_mail_to_user
    UserMailer.with(user: self.user,order: self.order).invoice_email.deliver_now
  end 
end

app/models/offer.rb
class Offer < ApplicationRecord
  attr_accessor :food_items_ids
  enum status: [:active, :inactive]
  has_and_belongs_to_many :food_items, dependent: :destroy
  validates :start_time, :end_time, :title, :status, presence: true
  after_save :add_food_items

  def add_food_items
    self.food_items_ids.each do |id|
      unless self.food_items.pluck(:id).include?(id.to_i) 
        self.food_items << FoodItem.find(id)
      end
    end   
  end  
end

app/models/order.rb
require "pdfkit"
require "render_anywhere"
class Order < ApplicationRecord
  include RenderAnywhere
  validates :ammount, :status,presence: true
  belongs_to :user
  has_one :invoice
  has_many :cart_items
  has_one :subscription
  #after_create :generate_pdf_of_invoice 
  def create_invoice
    Invoice.create(user_id: user.id, order_id: id)
  end

  def generate_pdf_of_invoice
    kit = PDFKit.new(as_htmls, page_size: 'A4')
    kit.to_file("invoice.pdf")
  end
  def as_htmls
    render template: "carts/pdf_invoice",layout: "invoice_pdf", locals: { order: self}
  end

  def generate_pdf_of_subscription
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("subscription.pdf")
  end

  def as_html
    render template: "carts/subscription_pdf",layout: "invoice_pdf", locals: { subscription: self.subscription}
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
	validates :plan_name, :price, :no_of_days, presence: true
	has_many :subscriptions
end

app/models/send_message.rb
class SendMessage < ApplicationRecord
	validates :name, :message, :email, :subject, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	validates :expiry_date, presence: true
	belongs_to :plan
	belongs_to :user
	belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable     
  validates :first_name, :last_name, :address, :contact_no, presence: true
  has_one :cart
  has_many :orders
  has_many :invoices
  has_many :subscriptions
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:add_to_cart, :show]
  def add_to_cart
    cart = current_user.cart.present? ? current_user.cart : Cart.create(user_id: current_user.id)
    @cart_item = cart.cart_items.find_or_create_by(food_item_id: params[:cart_item][:food_item_id], status:"unpaid")
    @cart_item.update(quantity: params[:cart_item][:quantity])
    @offer = Offer.find_by(id: params[:cart_item][:offer_id])
    if @offer.present?
      redirect_to offer_path(@offer)
    else
      redirect_to menu_path
    end
  end
  
  def show
    @cart = Cart.find(params[:id])
    @unpaid_cart_items = @cart.cart_items.unpaid
    @offer = Offer.find_by(id: params[:offer_id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
	def index
   @offers = Offer.all
	end
  
  def show
    @offer = Offer.find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def offer_params
    params.require(:offers).permit(:start_time, :end_time, :title, :status, :discount, :min_purchase, :max_discount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_flash_message
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

  def food_item_quantity(food_item_id)
    cart_item = current_user.cart.cart_items.where(food_item_id: food_item_id).first
    if cart_item
      cart_item.quantity
    else
      0
    end
  end
  def calculate_amount
    @amount = 0
    current_user.cart.cart_items.unpaid.each do |cartitem|
      @amount = @amount + cartitem.food_item.price*cartitem.quantity
    end
    @amount
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/pdf_invoice.html.erb
<div class="invoice">
  <h1>Invoice </h1>
  <h5>To: <%= order.user.first_name %> <%= order.user.last_name %><br><br>
    Date:<%= Time.now.strftime("%d/%m/%Y") %><br><br>
    From:Saphiya Restaurant behind c21 mall indore,<br>Phone no:0751-2442568
  </h5>
  <p align = 'center'>
    <table>
      <tr>
        <th>Description</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Cost</th>
      </tr>
      <% order.cart_items.each do |cartitem| %>
        <tr>
          <td><%= cartitem.food_item.name %></td>
          <td><%= cartitem.quantity %></td> 
          <td><%= cartitem.food_item.price %></td>
          <td><%= cartitem.food_item.price*cartitem.quantity %>
        </tr>
      <% end %>
    </table>
  </p>
  <div class="amnt">
    <label>
      <b>Amount</b>
      <%amount=0%>
      <% order.cart_items.each do |cartitem|%>
        <% amount=amount+cartitem.food_item.price*cartitem.quantity %>
      <%end%>
      <b> <%=amount%></b>
    </label>
  </div>
</div>

app/views/carts/show.html.erb
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Cart</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="payment">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="invoice">
        <%if @offer.present?%>
          <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="myModalLabel"><%=@offer.title%></h4>
                  <button type="button" class="close" data-dismiss="modal">x</button>
                </div>
                <div class="modal-body">
                  <p text-color="olive">
                    <i>
                      This offer will be applicable from
                      <%=@offer.start_time.strftime("%d/%m/%Y")%> To <%=@offer.end_time.strftime("%d/%m/%Y")%> You can get maximum discount <%=@offer.max_discount%> rupees at  minimum purchased <%=@offer.min_purchase%> rupees 
                    </i>
                  </p>
                </div> 
              </div>
            </div>
          </div> 
          <% if @unpaid_cart_items.present? %>
            <table id="cart">
              <tbody class="item">
                <% @unpaid_cart_items.each do |cartitem| %>
                  <tr>
                    <td><%= cartitem.food_item.name%></td> 
                    <td><%= cartitem.food_item.price%> X <%=cartitem.quantity %></td>
                    <td><%=cartitem.food_item.price*cartitem.quantity%></td>
                    <td>
                      <%= link_to  cart_item_path(cartitem,offer: @offer.id),
                      title: "Delete Record",data: {:confirm => 'Are you sure?'}, :method => :delete,remote: true,:class => "iconcolor" do %>
                       <i class="fa fa-trash" aria-hidden="true"></i>
                      <%end%>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
            <div class="total">
              <%granttotal=0%>
              <%if calculate_amount >= @offer.min_purchase %>
                <label>Total</label>
                <i class="fa fa-inr" aria-hidden="true"></i>
                <%=calculate_amount%><br>
                <label>Discount</label>
                <i class="fa fa-inr" aria-hidden="true"></i>
                <%=@offer.max_discount%><br>
                <label>Pay Amount</label>
                <i class="fa fa-inr" aria-hidden="true"></i>
                <%=granttotal = calculate_amount-@offer.max_discount%><br>
                <%= link_to  new_charge_path(amount: granttotal,offer: @offer.id),title: "Pay To Money",:class => "btn_1 d-none d-sm-block" do %>
                <i class="fa fa-inr" aria-hidden="true"></i>Pay To Proceed
                <%end%><%= link_to "Back",offer_path(@offer),:class => "btn_1 d-none d-sm-block" %>
              <%else%>
                <label>Total</label>
                <i class="fa fa-inr" aria-hidden="true"></i>
                <%=amount = calculate_amount%><br>
                <%= link_to  new_charge_path,title: "Pay To Money",:class => "btn_1 d-none d-sm-block" do %>
                <i class="fa fa-inr" aria-hidden="true"></i>Pay To Proceed
                <%end%>|<%= link_to "Back",offer_path(@offer),:class => "btn_1 d-none d-sm-block"%>
              <%end%>
            </div>
          <%end%>
        <%else%>
          <% if @unpaid_cart_items.present? %>
            <table>
              <tbody>
                <% @unpaid_cart_items.each do |cartitem| %>
                  <tr>
                    <td><%= cartitem.food_item.name%></td> 
                    <td><%= cartitem.food_item.price%> X <%=cartitem.quantity %></td>
                    <td><%=cartitem.food_item.price*cartitem.quantity%></td>
                    <td><%= link_to  edit_cart_item_path(cartitem),title: "Edit Record",:class => "iconcolor" do%>
                      <i class="fa fa-pencil" aria-hidden="true"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to  cart_item_path(cartitem),title: "Delete Record",data: {:confirm => 'Are you sure?'}, :method => :delete,:class => "iconcolor" do %>
                     <i class="fa fa-trash" aria-hidden="true"></i>
                    <%end%>
                  </td>
                  </tr>
                <%end%>
              </tbody>
            </table>
          <%end%>
          <div class="total1">
            <label>Total</label>
            <i class="fa fa-inr" aria-hidden="true"></i>
            <%=calculate_amount%><br>
            <p style="float: left;">
              <%= link_to "Proceed to pay", new_charge_path,:class => "btn_11" %>
            </p>
            <p style="float: right;">
              <%=link_to "Back",menu_path,:class => "btn_11"%>
            </p>
          </div>
        <%end%>
      </div>
    </div>
    <div class="col-md-2">
    </div>
    <%if @offer.present? %> 
      <div class="col-md-4">
        <section class="chefs_part blog_item_section section_padding">
          <div class="container">
            <div class="single_blog_item">
              <div class="single_blog_text text-center">
                <h3><%= @offer.title %></h3>
                <p><%= "#{@offer.max_discount} %OFF" %></p>
                <div class="banner_btn">
                  <div class="banner_btn_iner">
                    <a>
                      <%= link_to 'Offer Details', '#', {'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    <%end%>
  </div>  
</div>

app/views/carts/subscription_pdf.html.erb
<div class="invoice">
  <h1>Invoice</h1>
  <h5>To: <%= subscription.user.first_name %> <%= subscription.user.last_name %><br><br>
    Date:<%= Time.now.strftime("%d/%m/%Y") %><br><br>
    From:Saphiya Restaurant behind c21 mall indore,<br>Phone no:0751-2442568
  </h5>
    <table>
      <tr>
        <th>Description</th>
        <th>Price</th>
      </tr>
      <tr>
      <td><%= subscription.plan.plan_name%></td>
      <td><%= subscription.plan.price%></td>
      </tr>
    </table>
    <h3><b>Amount</b>
    <%=subscription.plan.price%>
  </h3>
</div>

app/views/offers/index.html.erb
  <!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Offers</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <!-- breadcrumb end-->
    
  <!--::offers_part start::-->
  <section class="chefs_part blog_item_section section_padding">
    <div class="container">
      <div class="row">
        <div class="col-xl-5">
          <div class="section_tittle">
            <h2>Our Recent Offers</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <% @offers.each do |offer| %>
          <div class="col-sm-6 col-lg-4">
            <div class="single_blog_item">
              <div class="single_blog_img">
                <%= image_tag("offer2.png", :alt => "offer2 feed") %>
              </div>
              <div class="single_blog_text text-center">
                <h3><%= offer.title %></h3>
                <p><%= "#{offer.max_discount} %OFF" %></p>
                <div class="banner_btn">
                  <div class="banner_btn_iner">
                    <a href="<%= offer_path(offer.id) %>" class="btn_3">Pick Offer <%= image_tag("icon/left_1.svg", :alt => "left_1 feed") %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div> 
        <%end%>
      </div>
    </div>
  </section>
  <!--::offers_part end::-->

app/views/offers/show.html.erb
 <!-- breadcrumb start -->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Offer</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
 <!-- breadcrumb end -->

 <!-- modal part start -->
<div id="modal-window" class="modal hide fade" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Your Cart Having items
        Do You Want To</h5>
      </div>
      <div class="modal-body">
        <p text-color="olive">
          <i>
            <%= link_to "Continue", cart_path(current_user.cart.id),:class => "btn_1 header" %>
            <%= link_to "Clear All", delete_all_cart_items_path, data: {:confirm => 'Are you sure?'}, :method => :delete,:class => "btn_1 headercenterlink" %>
          </i>
        </p>
      </div> 
    </div>
  </div>
</div> 
<!-- modal part end -->

  <!--::offer_part start::-->
<section class="chefs_part blog_item_section section_padding">
  <div class="container">
    <div class="row">
      <div class="col-xl-5">
        <div class="section_tittle">
          <h2>Offer Items List</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <% @offer.food_items.each do |food_item| %>
        <div class="col-sm-6 col-lg-4">
          <div class="single_blog_item">
            <div class="single_blog_img">
              <%= image_tag food_item.photo.url, :size => "350x200" %>
            </div>
            <div class="single_blog_text text-center">
              <h3><%=food_item.name%></h3>
              <p><%=food_item.price%></p>
              <%= form_for :cart_item,:url => add_to_cart_path  do |cart_item| %>
                <button type="button" class="
                add-quantity"><i class="fas fa-minus"></i></button>
                <%= cart_item.text_field :quantity,class: 'qty', value: food_item_quantity(food_item.id) %>
                <button type="button" class="add-quantity"><i class="fas fa-plus"></i></button>
                <%= cart_item.hidden_field :food_item_id, :value => food_item.id %>
                <%= cart_item.hidden_field :offer_id, :value => @offer.id %>
                <%= cart_item.hidden_field :cart, :value => current_user.cart %>
                <button type="submit" class="add-button"><i class="fas fa-shopping-cart"></i></button>
              <%end%>
            </div>
          </div>
        </div> 
      <%end%>
    </div>
  </div> 
</section>
  <!--::offer_part end::-->
<%if session[:items]=="true"%>
  <script>
    $(document).ready(function(){
      $('#modal-window').modal('show');
      $('.qty').each(function(index, value) {
        value = parseInt(value["value"])
        if(value > 0){
          $(this).siblings('.add-button').show();
        }else{
         $(this).siblings('.add-button').hide(); 
        }
      });
      $('.add-quantity').click(function(e){
        e.preventDefault();
        var element = $(this).siblings('.qty')
        if($(this).attr('class') == 'add-quantity'){
          $(element).val(parseInt(element.val()) + 1);  
        }else{
          debugger
          if($(element).val() > 0){
           $(element).val(parseInt(element.val()) - 1);
         }
        }
        var button = $(this).siblings('.add-button')
        if(parseInt(element.val())>0){
          $(button).show();
        }else{
          $(button).hide();
        }
      });
    });
  </script>
<%else%>
  <script>
    $(document).ready(function(){
      $('.qty').each(function(index, value) {
        value = parseInt(value["value"])
        if(value > 0){
          $(this).siblings('.add-button').show();
        }else{
         $(this).siblings('.add-button').hide(); 
        }
      });
      $('.add-quantity').click(function(e){
        e.preventDefault();
        var element = $(this).siblings('.qty')
        if($(this).attr('class') == 'add-quantity'){
          $(element).val(parseInt(element.val()) + 1);  
        }else{
          debugger
          if($(element).val() > 0){
           $(element).val(parseInt(element.val()) - 1);
         }
        }
        var button = $(this).siblings('.add-button')
        if(parseInt(element.val())>0){
          $(button).show();
        }else{
          $(button).hide();
        }
      });
    });
  </script>
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'linkcolor' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'linkcolor' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'linkcolor' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>