config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'
  get '/menu', to: 'welcomes#menu'
  #get '/offer', to: 'welcomes#offer'
  #get '/offers/:offer_id', to: 'offers#details', as: 'details'
  get '/about_us', to: 'welcomes#about_us'
  get '/contact_us', to: 'welcomes#contact_us'
  post '/send_message', to: 'welcomes#send_message'
  post '/add_to_cart', to: 'carts#add_to_cart'
  get '/subscription', to: 'charges#subscription'
  post '/create_subscription', to: 'charges#create_subscription'

  get '/invoice_email', to: 'users#invoice_email' 
  get '/order_history/', to: 'charges#order_history'
  #delete '/order_destroy/:id', to: 'charges#order_destroy'
  #get '/order_show/:id', to: 'charges#order_show'
  #get '/carts/:id', to: 'carts#pdf_invoice
  resources :carts, only: [:show]
  resources :charges
  resources :offers, only: [:index, :show]
  resources :cart_items, only: [:edit, :update, :destroy] do
    collection do
      delete :delete_all
    end
  end
  resources :invoices, only: [:show] 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  layout 'application'
  def new
    offer = Offer.find_by(id:params[:offer])
    amount = params[:amount]
    if offer.present?
      @amount = amount
    else
      @amount = 0
      current_user.cart.cart_items.unpaid.each do |cartitem|
        @amount = @amount + cartitem.food_item.price * cartitem.quantity
      end
    end
  end
    
  def create
  # Amount in cents
  begin
    amount =  params[:payment][:amount]
    token = Stripe::Token.create( :card => { :number => params[:payment][:Card], :exp_month => params[:payment][:Expiry_month], :exp_year => params[:payment][:Expiry_year], :cvc =>  params[:payment][:security]})
    if !current_user.stripe_customer_id.present?
      customer = Stripe::Customer.create(:email => params[:email], :source  => token)
    end
    charge = Stripe::Charge.create(
      :amount => amount.to_i,
      :currency => "usd",
      :source => token.id, # obtained with Stripe.js
      :description => "Charge for jenny.rosen@example.com"
    )
    if charge.status.eql?('succeeded')
      order = Order.create(ammount: amount, user_id: current_user.id, status: "Paid")
      current_user.cart.cart_items.unpaid.update_all(order_id: order.id, status: "paid")
      order.create_invoice
      flash[:success] = "Payment successfully done..!"
      redirect_to menu_path
    else
      redirect_to new_charge_path
    end
    rescue Stripe::CardError, Stripe::InvalidRequestError,
         Stripe::AuthenticationError => e
      flash[:error] = e.message
      render 'new'
    end
  end

  def order_history
    @orders = current_user.orders
  end

  def subscription

  end

  def create_subscription
    plan =  Plan.find_by(id: params[:payment][:plan_id])
    begin

      if plan.present?
        stripe_plan_id = plan.stripe_plan_id
        price = plan.price
        if !current_user.stripe_customer_id
          token = Stripe::Token.create( :card => { :number => params[:payment][:Card], :exp_month => params[:payment][:Expiry_month], :exp_year => params[:payment][:Expiry_year], :cvc =>  params[:payment][:security]})
          customer = Stripe::Customer.create(:email => params[:email], :source  => token)
          current_user.update(stripe_customer_id: customer.id)
        end
        stripe_subscription = Stripe::Subscription.create(
                                                          :customer => current_user.stripe_customer_id,
                                                          :items => [{:plan => stripe_plan_id}]
                                                          )
        order = Order.create(ammount: price, status: "paid", user_id: current_user.id)
        subscription = Subscription.create(user_id: current_user.id, plan_id: plan.id, order_id: order.id, stripe_subscription_id: stripe_subscription.id, expiry_date: Time.now + plan.no_of_days.days)
        order.create_invoice
        flash[:success] = "Your one month subscription !current_user.stripe_customer_idcreated successfully."
        redirect_to menu_path
      end
    rescue
      flash[:error] = "Your subscription unsuccessfull try again.."
      redirect_to subscription_path
    end
  end
end
  

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
  <!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Payment</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <!-- breadcrumb end -->
  
  <!-- ================ payment section start ================= -->
<section class="contact-section section_padding">
  <div class="container">   
    <div class="row">
      <div class="col-12">
        <h2 class="contact-title">Payment Details</h2>
      </div>
      <div class="col-lg-8">
        <%= form_for :payment , url: charges_path, html: {class: 'payment_form', id: 'paymentForm'}, remote: true do |f| %>
          <div class="form-group">
            <%= f.text_field :Card, autofocus: true, autocomplete: "Card",placeholder: "Card Number", class: 'form-control cardField', id: 'card' %>
          </div>
          <div class="form-group">
            <%= f.text_field :Expiry_month, autofocus: true, autocomplete: "Expiry_month",placeholder: "Exp_month/MM", class: 'form-control monthField', id: 'month' %>
          </div>
          <div class="form-group">
            <%= f.text_field :Expiry_year, autofocus: true, autocomplete: "Expiry_year",placeholder: "Exp_year/YYYY", class: 'form-control yearField', id: 'year' %>
          </div>
          <div class="form-group">
            <%= f.text_field :security, autofocus: true, autocomplete: "security",placeholder: "CVC", class: 'form-control securityField', id: 'secrurity' %>
          </div>
          <div class="form-group">
            <%=f.text_field :amount, placeholder: "Amount", value: @amount,class: 'form-control' %><br>
          </div>
          <div class="form-group mt-3">
            <div class="actions">
              <button type="submit" class="button button-contactForm btn_4">Submit</button>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</section>
<!-- ================ Payment section end ================= -->

app/views/charges/new.html.erb
<%= render "charges/form"%>

app/views/charges/new.js.erb
$('.payment').html('<%= j render 'charges/form' %>');

app/views/charges/order_history.html.erb
<h2 align = 'center'><i>History of order</i></h2><br><br>
<table id="order_history">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody> 
    <%current_user.orders.each do |order|%>
      <%order.cart_items.each do |cartitem|%>
        <tr>
          <td> <%=order.created_at.strftime("%d/%m/%Y")%></td>
          <td><%= cartitem.food_item.name%></td>
          <td><%= cartitem.quantity%></td>
          <td><%= cartitem.food_item.price%></td>
          <td><%= cartitem.food_item.price*cartitem.quantity%></td> 
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>

<script>
  $(document).ready(function() {
    $("#order_history").dataTable();
  });
</script>

app/views/charges/subscription.html.erb
<%#= form_for :payment , url: create_subscription_path do |f| %>
  <%#=f.text_field :Card, placeholder: "Enter card number"%><br>
  <%#=f.text_field :Expiry_month, placeholder: "Expiry_month/MM"%><br>
  <%#=f.text_field :Expiry_year, placeholder: "Expiry_year/YY"%><br>
  <%#=f.text_field :security, placeholder: "CVC"%><br>
  <%# #plan = Plan.find_by plan_name: 'Monthly Thali'%>
  <%#= f.hidden_field :plan_id, :value => plan.id %> 
  
  <%#=f.submit "Payment of subscrition"%>
<%#end%>
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb_iner text-center">
          <div class="breadcrumb_iner_item">
            <h2>Payment For Subscription</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <!-- breadcrumb start-->

  <!-- ================ payment section start ================= -->
<section class="contact-section section_padding">
  <div class="container">   
    <div class="row">
      <div class="col-12">
        <h2 class="contact-title">Payment Details</h2>
      </div>
      <div class="col-lg-8">
        <%= form_for :payment , url: create_subscription_path, class: "form-contact contact_form", id: "contactForm", remote: true do |f| %>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.text_field :Card, placeholder: "Enter card number" %><br>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%=f.text_field :Expiry_month, placeholder: "Expiry_month/MM"%><br>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%=f.text_field :Expiry_year, placeholder: "Expiry_year/YY"%><br>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%=f.text_field :security, placeholder: "CVC"%><br>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
               <% plan = Plan.find_by plan_name: 'Monthly Thali'%>
               <%= f.hidden_field :plan_id, :value => plan.id %> 
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <%=f.submit "Done!"%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</section>
<!-- ================ Payment section end ================= -->