config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'
  get '/menu', to: 'welcomes#menu'
  #get '/offer', to: 'welcomes#offer'
  #get '/offers/:offer_id', to: 'offers#details', as: 'details'
  get '/about_us', to: 'welcomes#about_us'
  get '/contact_us', to: 'welcomes#contact_us'
  post '/send_message', to: 'welcomes#send_message'
  post '/add_to_cart', to: 'carts#add_to_cart'
  get '/subscription', to: 'charges#subscription'
  post '/create_subscription', to: 'charges#create_subscription'

  get '/invoice_email', to: 'users#invoice_email' 
  get '/order_history/', to: 'charges#order_history'
  #delete '/order_destroy/:id', to: 'charges#order_destroy'
  #get '/order_show/:id', to: 'charges#order_show'
  #get '/carts/:id', to: 'carts#pdf_invoice
  resources :carts, only: [:show]
  resources :charges
  resources :offers, only: [:index, :show]
  resources :cart_items, only: [:edit, :update, :destroy] do
    collection do
      delete :delete_all
    end
  end
  resources :invoices, only: [:show] 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  enum status: [:paid, :unpaid]
  validates :status, presence: true
  belongs_to :cart
  belongs_to :food_item
  belongs_to :order, required: false
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name,:price, presence: true
  belongs_to :category
  has_one :cart_item
  has_and_belongs_to_many :offers, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  
  belongs_to :user
  belongs_to :order
  
  after_create :send_mail_to_user

  def send_mail_to_user
    UserMailer.with(user: self.user,order: self.order).invoice_email.deliver_now
  end 
end

app/models/offer.rb
class Offer < ApplicationRecord
  attr_accessor :food_items_ids
  enum status: [:active, :inactive]
  has_and_belongs_to_many :food_items, dependent: :destroy
  validates :start_time, :end_time, :title, :status, presence: true
  after_save :add_food_items

  def add_food_items
    self.food_items_ids.each do |id|
      unless self.food_items.pluck(:id).include?(id.to_i) 
        self.food_items << FoodItem.find(id)
      end
    end   
  end  
end

app/models/order.rb
require "pdfkit"
require "render_anywhere"
class Order < ApplicationRecord
  include RenderAnywhere
  validates :ammount, :status,presence: true
  belongs_to :user
  has_one :invoice
  has_many :cart_items
  has_one :subscription
  #after_create :generate_pdf_of_invoice 
  def create_invoice
    Invoice.create(user_id: user.id, order_id: id)
  end

  def generate_pdf_of_invoice
    kit = PDFKit.new(as_htmls, page_size: 'A4')
    kit.to_file("invoice.pdf")
  end
  def as_htmls
    render template: "carts/pdf_invoice",layout: "invoice_pdf", locals: { order: self}
  end

  def generate_pdf_of_subscription
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("subscription.pdf")
  end

  def as_html
    render template: "carts/subscription_pdf",layout: "invoice_pdf", locals: { subscription: self.subscription}
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
	validates :plan_name, :price, :no_of_days, presence: true
	has_many :subscriptions
end

app/models/send_message.rb
class SendMessage < ApplicationRecord
	validates :name, :message, :email, :subject, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	validates :expiry_date, presence: true
	belongs_to :plan
	belongs_to :user
	belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable     
  validates :first_name, :last_name, :address, :contact_no, presence: true
  has_one :cart
  has_many :orders
  has_many :invoices
  has_many :subscriptions
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_flash_message
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

  def food_item_quantity(food_item_id)
    cart_item = current_user.cart.cart_items.where(food_item_id: food_item_id).first
    if cart_item
      cart_item.quantity
    else
      0
    end
  end
  def calculate_amount
    @amount = 0
    current_user.cart.cart_items.unpaid.each do |cartitem|
      @amount = @amount + cartitem.food_item.price*cartitem.quantity
    end
    @amount
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-area">
  <div class="container">
    <div class="row">
      <div class="col-xl-3 col-sm-6 col-md-3 col-lg-3">
        <div class="single-footer-widget footer_1">
          <h4>About Us</h4>
          <p>
            Heaven fruitful doesn't over for these theheaven fruitful doe over days appear creeping seasons sad behold beari ath of it fly signs bearing be one blessed after.
          </p>
        </div>
      </div>
      <!-- <div class="col-xl-3 col-sm-6 col-md-2 col-lg-3">
        <div class="single-footer-widget footer_2">
          <h4>Important Link</h4>
          <div class="contact_info">
            <ul>
              <li><a href="#">WHMCS-bridge</a></li>
              <li><a href="#"> Search Domain</a></li>
              <li><a href="#">My Account</a></li>
              <li><a href="#">Shopping Cart</a></li>
              <li><a href="#"> Our Shop</a></li>
            </ul>
          </div>
        </div>
      </div> -->
        <div class="col-xl-3 col-sm-6 col-md-3 col-lg-3">
          <div class="single-footer-widget footer_2">
            <h4>Contact us</h4>
            <div class="contact_info">
              <p>
                <span> Address :</span>
                  H/1 , Scheme No.54, Vijay Nagar, Indore
              </p>
              <p><span> Phone :</span> 0731 400 6666</p>
              <p><span> Email : </span>info@colorlib.com </p>
            </div>
          </div>
        </div>
      <!-- <div class="col-xl-3 col-sm-6 col-md-4 col-lg-3">
        <div class="single-footer-widget footer_3">
          <h4>Newsletter</h4>
          <p>Heaven fruitful doesn't over lesser in days. Appear creeping seas</p>
          <form action="#">
            <div class="form-group">
              <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder='Email Address'onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address'">
                <div class="input-group-append">
                  <button class="btn" type="button"><i class="fas fa-paper-plane"></i></button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div> -->
    </div>
    <div class="copyright_part_text">
      <div class="row">
        <div class="col-lg-8">
          <p class="footer-text m-0">
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
          </p>
        </div>
        <div class="col-lg-4">
          <div class="copyright_social_icon text-right">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="ti-dribbble"></i></a>
            <a href="#"><i class="fab fa-behance"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main_menu home_menu">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="index.html"><%= image_tag("logo.png", :alt => "logo feed") %> </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse main-menu-item justify-content-end"
              id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="<%=root_path%>">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="<%=about_us_path%>">About</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="<%=menu_path%>">Menu</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="<%=offers_path%>">Offers</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="<%=contact_us_path%>">Contact</a>
              </li>
            </ul>
          </div>
          <div style="overflow: hidden;" class="menu_btn">
            <% if user_signed_in? %>
            <p style="float: left;">
              <%= link_to 'View Cart',cart_path(current_user.cart.id),:class => "btn_1 d-none d-sm-block header headerlinkcenter"%>
            </p>
            <p style="float: right;">
              <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => "btn_1 d-none d-sm-block header headerlinkcenter" %> 
            </p>       
            <% else %>
              <p style="float: left;">
                <%= link_to 'Login', new_user_session_path, :class => "btn_1 d-none d-sm-block header headerlinkcenter" %></p>
              <p style="float: right;"><%= link_to 'Register', new_user_registration_path, :class  => "btn_1 d-none d-sm-block header headerlinkcenter "  %></p> 
            <% end %>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ofos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
  <body>
    <%= render 'layouts/header'%>
      <div class="container-fluid">
        <% if notice.present? %>
        <div class="alert alert-success" role="alert">
          <strong>Success!</strong> <%= notice %>
        </div>
        <% end %>
        <% if alert.present? %>
          <div class="alert alert-danger" role="alert">
            <strong>Oh snap!</strong> <%= alert %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    <%= render 'layouts/footer'%>
  </body>
</html>
<script type="text/javascript">
  setTimeout(function() {
    $('.alert').hide('slow').delay(1000)
  }, 2000);
</script>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/invoice_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title> Invoices of food</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>